version: '3.8'

services:
  react-app:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - websocket-server
    environment:
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true

  websocket-server:
    build: ./server
    ports:
      - "3001:3001"
