version: "3.8"

services:
  react-app:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - websocket-server
    volumes:
      - travel-planner-client-data:/app

  websocket-server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - travel-planner-server-data:/app

volumes:
  travel-planner-client-data:
    external: true
  travel-planner-server-data:
    external: true
